name: Check linter

on:
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: install dependencies
              run: npm install --no-audit --no-fund --no-optional

            - name: check lint
              run: npm run lint
